apiVersion: v1
kind: Service
metadata:
  name: my-release-mongodb
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: my-release
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: my-release
